name: win_messages
description: A new flutter plugin project.
version: 0.0.2
author: krysl@qq.com
# homepage:

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: WinMessagesPlugin

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
