name: win_messages_sample
description: An example project for win_messages_sample.

version: 0.1.0

environment:
  sdk: '>=2.7.0 <3.0.0'
  # The example interacts with build scripts on the Flutter side that are not
  # yet stable, so it requires a very recent version of Flutter.
  # This version will increase regularly as the build scripts change.
  flutter: '>=1.10.2-pre.54'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0

  window_size:
    path: ../deps/window_size
  win_messages:
    version: ^0.0.2
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # See https://github.com/flutter/flutter/wiki/Desktop-shells#fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
    - family: SourceHanSansCN
      fonts:
        - asset: fonts/SourceHanSansCN/SourceHanSansCN-ExtraLight.otf
          weight: 100
        - asset: fonts/SourceHanSansCN/SourceHanSansCN-Light.otf
          weight: 200
        - asset: fonts/SourceHanSansCN/SourceHanSansCN-Normal.otf
          weight: 300
        - asset: fonts/SourceHanSansCN/SourceHanSansCN-Regular.otf
          weight: 400
        - asset: fonts/SourceHanSansCN/SourceHanSansCN-Medium.otf
          weight: 500
        - asset: fonts/SourceHanSansCN/SourceHanSansCN-Bold.otf
          weight: 700
        - asset: fonts/SourceHanSansCN/SourceHanSansCN-Heavy.otf
          weight: 900
  assets:
   - images/WWCQ3.png